### ISSUE TITLE
Release 1.4.0 .exe sets off Windows Defender

### ISSUE THREAD

**Issue by Auhrii** [SpottedSqueak/FA-Gallery-Downloader#11]
```
Threat blocked | Severe

Detected: Trojan:Win32/Phonzy.A!ml
Status: Removed
A threat or app was removed from this device.

Date: 2024-08-07 11:53
Details: This program is dangerous and executes commands from an attacker.
```

Windows Defender immediately removes the download .tmp file when I attempt to download the v1.4.0 executable -- I don't even get the chance to run a Malwarebytes spot check on it.

**Comment by SpottedSqueak** [comment]
Yeah, I've heard that that's an issue lately. I'm looking into different build options, because the one I'm using (Caxa) is known to cause these issues! I have a few in mind, but they'll take a bit to test out...And I'll definitely need to make sure I copy over any already created data from the Caxa install for earlier versions too. In the meantime is there any way to flag it as a false positive?

**Comment by Auhrii** [comment]
Unfortunately, there doesn't seem to be, but I was able to get around it by preoccupying Defender with a full scan whilst I downloaded the executable. Running a scan on the fully downloaded file with both Defender and Malwarebytes showed an all clear.

**Comment by SpottedSqueak** [comment]
Just pushed a new update, let me know if that addresses your issues here!

**Comment by SpottedSqueak** [comment]
Gonna assume this is working okay! Feel free to reopen if it doesn't.
